on: push

jobs:
  build:
    name: Build docker image
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          submodules: true
      - name: Build Step 1
        env:
          TEST_SECRET: ${{ secrets.TEST_SECRET }}
        run: |
          echo 1111; echo $TEST_SECRET; echo $secrets
#      - name: Build and push Docker images
#        uses: docker/build-push-action@v2.6.1

#  push:
#    name: Push to Dockerhub
#    runs-on: ubuntu-20.04
#    needs: build